name: publish to npm

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: add dependency
        run: npm install
      - run: npm ci
      - name: publish
        run: npm publish --access public
        env:
          NPM_TOKEN: '61fa5712-e97f-4ceb-b91d-213aee1eb108'